### ISSUE TITLE
parse in lib/parser.js too slow

### ISSUE THREAD

**Issue by fuentesjr** [attinteractive/node-lwes#3]
The parse method in lib/parser.js is a blocking/synchronous method and can result in high cpu usage under heavy upd data load

**Comment by aq1018** [comment]
Just completed the native extension.
- Added lwes c library as a dependent
- Made lwes c lib to build automatically before building node-lwes native extension
- Made parser.cc compile
- Made sure extension loads

@fuentesjr 

Can you give it a run and let me know if it really works?

Thanks!

**Comment by aq1018** [comment]
Also, the c lib doesn't support many of the typs supported in Java, such as float / double, arrays, bytes, etc...

**Comment by aq1018** [comment]
Maybe we should write a better c lib?

**Comment by fuentesjr** [comment]
Closing old issues I created
